language: node_js

install:
  - make clean
  - make node_modules
  - make lingeling-linux TARGET=.
  - make riss-linux TARGET=.

script:
  - PATH=$PATH:. make

node_js:
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"

branches:
  only:
    - gh-pages
