language: node_js

install:
  - make lingeling-linux TARGET=.
  - make riss-linux TARGET=.

script:
  - PATH=$PATH:. make

node_js:
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"

branches:
  only:
    - gh-pages
